export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
export const HANDLE_CLIENT_SELECT_CHANGE = "HANDLE_CLIENT_SELECT_CHANGE";
export const HANDLE_INVOICE_NUMBER_CHANGE = "HANDLE_INVOICE_NUMBER_CHANGE";
export const HANDLE_ITEM_TYPE_CHANGE = "HANDLE_ITEM_TYPE_CHANGE";
export const HANDLE_INVOICE_TYPE_CHANGE = "HANDLE_INVOICE_TYPE_CHANGE";
export const HANDLE_DATE_INPUT_CHANGE = "HANDLE_DATE_INPUT_CHANGE";
